/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * GearCalculatorUI.java
 *
 * Created on Aug 15, 2010, 8:00:01 PM
 */

package modrcon;
import java.awt.*;
/**
 *
 * @author Jacob
 */
public class GearCalculatorUI extends javax.swing.JFrame {
    /** Creates new form GearCalculatorUI */
    public GearCalculatorUI() {
        initComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        logoPanel = new LogoPanel(1);
        gearPanel = new javax.swing.JPanel();
        scrollGear = new javax.swing.JScrollPane();
        tableGear = new javax.swing.JTable();
        lblSetGear = new javax.swing.JLabel();
        lblSelectAll = new javax.swing.JLabel();
        lblUnselectAll = new javax.swing.JLabel();
        spinnerGear = new javax.swing.JSpinner();
        btnSend = new javax.swing.JButton();
        btnClose = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("1up ModRcon - Gear Calculator");
        setResizable(false);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        logoPanel.setPreferredSize(new java.awt.Dimension(100, 66));

        javax.swing.GroupLayout logoPanelLayout = new javax.swing.GroupLayout(logoPanel);
        logoPanel.setLayout(logoPanelLayout);
        logoPanelLayout.setHorizontalGroup(
            logoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 390, Short.MAX_VALUE)
        );
        logoPanelLayout.setVerticalGroup(
            logoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 52, Short.MAX_VALUE)
        );

        gearPanel.setBorder(javax.swing.BorderFactory.createTitledBorder("Gear Calculator"));

        tableGear.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {new Boolean(true), "Grenades", "1"},
                {new Boolean(true), "Snipers", "2"},
                {new Boolean(true), "Spas", "4"},
                {new Boolean(true), "Pistols", "8"},
                {new Boolean(true), "Automatic Guns", "16"},
                {new Boolean(true), "Negev", "32"}
            },
            new String [] {
                "", "Gear", "Value"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Boolean.class, java.lang.Object.class, java.lang.Object.class
            };
            boolean[] canEdit = new boolean [] {
                true, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tableGear.setAutoResizeMode(javax.swing.JTable.AUTO_RESIZE_LAST_COLUMN);
        tableGear.getTableHeader().setResizingAllowed(false);
        scrollGear.setViewportView(tableGear);

        lblSetGear.setText("Set g_Gear");

        lblSelectAll.setText("All");

        lblUnselectAll.setText("None");

        spinnerGear.setModel(new javax.swing.SpinnerNumberModel(0, 0, 63, 1));

        javax.swing.GroupLayout gearPanelLayout = new javax.swing.GroupLayout(gearPanel);
        gearPanel.setLayout(gearPanelLayout);
        gearPanelLayout.setHorizontalGroup(
            gearPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, gearPanelLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(gearPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(gearPanelLayout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(lblSetGear)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(spinnerGear, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(162, 162, 162)
                        .addComponent(lblSelectAll)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblUnselectAll))
                    .addComponent(scrollGear, javax.swing.GroupLayout.PREFERRED_SIZE, 338, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );
        gearPanelLayout.setVerticalGroup(
            gearPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(gearPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(scrollGear, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(gearPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(lblSetGear)
                    .addGroup(gearPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(lblUnselectAll)
                        .addComponent(lblSelectAll)
                        .addComponent(spinnerGear, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        btnSend.setText("Send To Server");

        btnClose.setText("Close");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(logoPanel, javax.swing.GroupLayout.DEFAULT_SIZE, 390, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addComponent(gearPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(10, 10, 10))
            .addGroup(layout.createSequentialGroup()
                .addGap(81, 81, 81)
                .addComponent(btnSend)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnClose, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(82, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(logoPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(gearPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnSend)
                    .addComponent(btnClose))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        tableGear.getTableHeader().setPreferredSize(new Dimension(tableGear.getTableHeader().getWidth(),20));
        tableGear.getColumnModel().getColumn(0).setPreferredWidth(20);
        tableGear.getColumnModel().getColumn(1).setPreferredWidth(200);
        tableGear.getColumnModel().getColumn(2).setPreferredWidth(100);
    }//GEN-LAST:event_formWindowOpened

    /**
    * @param args the command line arguments
    */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new GearCalculatorUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnClose;
    private javax.swing.JButton btnSend;
    private javax.swing.JPanel gearPanel;
    private javax.swing.JLabel lblSelectAll;
    private javax.swing.JLabel lblSetGear;
    private javax.swing.JLabel lblUnselectAll;
    private javax.swing.JPanel logoPanel;
    private javax.swing.JScrollPane scrollGear;
    private javax.swing.JSpinner spinnerGear;
    private javax.swing.JTable tableGear;
    // End of variables declaration//GEN-END:variables

}
